const $ = (id) => document.getElementById(id);
const tokenKey = 'memory_bridge_webui_token';
const rememberKey = 'memory_bridge_webui_remember_v051';
let token = localStorage.getItem(tokenKey) || '';
let fileDeleteEnabled = false;
let usableSessions = [];
let allRawSessions = [];
let allFiles = [];
let selectedTriggerSession = localStorage.getItem('memory_bridge_selected_trigger_session') || '';
let selectedImportSession = localStorage.getItem('memory_bridge_selected_import_session') || '';
let selectedImportFile = localStorage.getItem('memory_bridge_selected_import_file') || '';

const configLabels = {
  'export.max_messages': ['最大导出消息数', '导出、清洗和 WebUI 触发时最多读取的历史消息数量。'],
  'cleaning.mode': ['默认清洗模式', 'safe 保守 / balanced 平衡 / aggressive 激进。'],
  'cleaning.keep_recent_messages': ['强制保留最近消息数', '清洗时永远保留最近 N 条，避免误删最新上下文。'],
  'cleaning.mask_secrets': ['敏感信息脱敏', '对 token、api_key、password、cookie 等内容做脱敏。'],
  'file_delivery.send_mode': ['聊天文件发送方式', 'auto / file / path / path_only / disabled。'],
  'web_admin.enabled': ['启用 WebUI', '是否启动续忆桥独立管理页面。'],
  'web_admin.host': ['WebUI 监听地址', '建议 Docker/服务器环境保持 0.0.0.0。'],
  'web_admin.port': ['WebUI 端口', '默认 2333。'],
  'web_admin.password': ['WebUI 访问密码', '留空表示不需要登录；暴露到局域网或公网时建议设置。'],
  'web_admin.allow_remote_trigger': ['允许远程触发', '是否允许在网页上向指定会话触发 /续忆 指令。'],
  'web_admin.allowed_commands': ['远程触发白名单', '允许 WebUI 触发的命令列表。'],
  'web_admin.allow_file_delete': ['允许删除导出文件', '默认关闭，开启后 WebUI 文件列表会显示删除按钮。'],
  'web_admin.allow_history_preview': ['允许历史预览', '是否允许 WebUI 读取并展示目标会话最近历史。'],
  'web_admin.allow_import': ['允许记忆导入', '是否允许 WebUI 执行 clean zip 迁移导入。'],
  'web_admin.token_expire_hours': ['登录有效期（小时）', 'WebUI 登录 token 的有效时间。'],
  'import.default_mode': ['默认导入模式', 'hybrid / seed / plugin_memory。']
};

function authHeaders(){return token?{'Authorization':'Bearer '+token}:{}}
async function api(path,options={}){const headers=Object.assign({},authHeaders(),options.headers||{});if(options.body&&!headers['Content-Type'])headers['Content-Type']='application/json';const res=await fetch(path,Object.assign({},options,{headers}));if(res.status===401){showLogin();throw new Error('未授权，请登录')}const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||data.message||'请求失败');return data}
function fmtBytes(n){n=Number(n||0);if(n<1024)return n+' B';if(n<1024*1024)return(n/1024).toFixed(1)+' KB';return(n/1024/1024).toFixed(2)+' MB'}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function originTail(origin){const parts=String(origin||'').split(':');return parts[parts.length-1]||origin||''}
function originKind(origin){const o=String(origin||'');if(/GroupMessage/i.test(o))return '群聊';if(/FriendMessage/i.test(o))return '私聊';return '会话'}
function displayName(session){return session.display_name||session.name||session.nickname||session.group_name||`${originKind(session.origin)} ${originTail(session.origin)}`}
function avatarUrl(session){if(session.avatar_url)return session.avatar_url;const tail=originTail(session.origin);if(/^\d+$/.test(tail)){return /GroupMessage/i.test(session.origin)||session.category==='group'?`https://p.qlogo.cn/gh/${tail}/${tail}/100`:`https://q1.qlogo.cn/g?b=qq&nk=${tail}&s=100`}return ''}
function initials(session){const name=displayName(session);return (name||'会').trim().slice(0,2)}
function isNoisyAdapterSession(origin){const text=String(origin||'').trim();return !text||text==='unknown'||/^\d+$/.test(text)||/^\d+_\d+$/.test(text)}
function filterUsableSessions(sessions){return (sessions||[]).filter(session=>session&&session.origin&&!isNoisyAdapterSession(session.origin))}
function sessionMatches(session, keyword){keyword=String(keyword||'').trim().toLowerCase();if(!keyword)return true;return [session.origin,displayName(session),session.last_message_preview,session.category,session.group_name,session.sender_name].some(v=>String(v||'').toLowerCase().includes(keyword))}
function showLogin(msg=''){$('loginPanel').classList.remove('hidden');$('mainPanel').classList.add('hidden');$('loginBtn').classList.remove('hidden');$('logoutBtn').classList.add('hidden');$('loginMsg').textContent=msg}
function showMain(){$('loginPanel').classList.add('hidden');$('mainPanel').classList.remove('hidden');$('loginBtn').classList.add('hidden');$('logoutBtn').classList.remove('hidden')}
function switchPage(page){document.querySelectorAll('.nav-item').forEach(btn=>btn.classList.toggle('active',btn.dataset.page===page));document.querySelectorAll('.page').forEach(panel=>panel.classList.toggle('active',panel.dataset.pagePanel===page));window.scrollTo({top:0,behavior:'smooth'})}
async function checkAuth(){const info=await fetch('/api/auth-info').then(res=>res.json());if(!info.auth_required){token='no-auth';localStorage.setItem(tokenKey,token);showMain();await refreshAll();return}if(!token){showLogin('请输入密码继续访问。');return}try{await api('/api/status');showMain();await refreshAll()}catch(error){localStorage.removeItem(tokenKey);token='';showLogin('登录已过期，请重新输入密码。')}}
async function doLogin(){const password=$('passwordInput').value||'';$('loginMsg').textContent='正在验证...';try{const data=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})}).then(async res=>{const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||'登录失败');return body});token=data.token||'no-auth';localStorage.setItem(tokenKey,token);showMain();await refreshAll()}catch(error){$('loginMsg').textContent=error.message}}
function logout(){localStorage.removeItem(tokenKey);token='';showLogin('已退出登录。')}
function rememberSelections(){localStorage.setItem('memory_bridge_selected_trigger_session',selectedTriggerSession||'');localStorage.setItem('memory_bridge_selected_import_session',selectedImportSession||'');localStorage.setItem('memory_bridge_selected_import_file',selectedImportFile||'')}
async function refreshAll(){const oldTrigger=currentSession(false);const oldImport=currentImportSession(false);const oldFile=$('importFileSelect')?$('importFileSelect').value:'';$('refreshBtn').disabled=true;try{const [status,diag,files,sessions,actions,cfg,imports]=await Promise.all([api('/api/status'),api('/api/diagnostics'),api('/api/files'),api('/api/sessions'),api('/api/actions'),api('/api/config-view').catch(error=>({ok:false,error:error.message})),api('/api/imports').catch(()=>({ok:false,imports:[]}))]);allRawSessions=sessions.sessions||[];usableSessions=filterUsableSessions(allRawSessions);allFiles=files.files||[];if(oldTrigger)selectedTriggerSession=oldTrigger;if(oldImport)selectedImportSession=oldImport;if(oldFile)selectedImportFile=oldFile;renderStatus(status);renderChecks(diag.checks||[]);renderFiles(allFiles);renderSessions(usableSessions,allRawSessions);renderActions(actions.actions||[]);renderConfig(cfg);renderImportOptions();renderImports(imports.imports||[]);restoreSelectValue($('sessionSelect'),selectedTriggerSession);restoreSelectValue($('importSessionSelect'),selectedImportSession);restoreSelectValue($('importFileSelect'),selectedImportFile);rememberSelections()}catch(error){$('triggerMsg').textContent='刷新失败：'+error.message}finally{$('refreshBtn').disabled=false}}
function restoreSelectValue(select,value){if(!select||!value)return;const exists=[...select.options].some(o=>o.value===value);if(exists)select.value=value}
function renderStatus(status){$('version').textContent='v'+(status.version||'-');$('webState').textContent=status.web_started?'运行中':'未启动';$('fileCount').textContent=status.files_count??0;$('sessionCount').textContent=usableSessions.length;fileDeleteEnabled=!!(status.security&&status.security.file_delete)}
function renderChecks(checks){$('checks').innerHTML=checks.map(check=>`<div class="check"><div class="dot ${check.ok?'ok':''}"></div><div><strong>${escapeHtml(check.name)} <span class="${check.ok?'tag-ok':'tag-bad'}">${check.ok?'OK':'FAIL'}</span></strong><p>${escapeHtml(check.detail||'')}</p></div></div>`).join('')||'<div class="hint">暂无检测项</div>'}
function renderFiles(files){$('filesBody').innerHTML=files.map(file=>{const source=file.source_label||file.origin_label||file.origin||'-';const stats=file.stats||{};const statText=stats.raw_count?`原始/保留 ${stats.raw_count}/${stats.kept_count??'?'}`:'';return `<tr><td class="mono file-name">${escapeHtml(file.name)}</td><td>${escapeHtml(file.kind||'-')}</td><td>${fmtBytes(file.size)}</td><td>${escapeHtml(file.mtime||file.created_at||'-')}</td><td class="source-cell"><b>${escapeHtml(source)}</b><span>${escapeHtml(file.origin||'')}</span>${statText?`<em>${escapeHtml(statText)}</em>`:''}</td><td class="op-cell"><a class="download" href="${encodeURI(file.download_url)}" target="_blank">下载</a><button class="link-btn" onclick="inspectFile('${escapeHtml(file.name)}')">检查</button>${file.migration_available?`<button class="link-btn" onclick="selectImportFile('${escapeHtml(file.name)}')">迁移</button>`:''}${fileDeleteEnabled?`<button class="link-btn danger" onclick="deleteFile('${escapeHtml(file.name)}')">删除</button>`:''}</td></tr>`}).join('')||'<tr><td colspan="6" class="hint">暂无 zip 文件</td></tr>'}
function fillSessionSelect(select,sessions,selected){select.innerHTML=sessions.map(session=>`<option value="${escapeHtml(session.origin)}">${escapeHtml(displayName(session))}  ·  ${escapeHtml(session.origin)}</option>`).join('');if(!sessions.length)select.innerHTML='<option value="">暂无可用会话，请手动输入 default:FriendMessage:QQ</option>';restoreSelectValue(select,selected)}
function sessionCard(session,role){const av=avatarUrl(session);const name=displayName(session);const active=(role==='trigger'?selectedTriggerSession:selectedImportSession)===session.origin;return `<button class="session-card ${active?'active':''}" onclick="chooseSession('${role}','${escapeHtml(session.origin)}')"><span class="avatar">${av?`<img src="${escapeHtml(av)}" onerror="this.remove();this.parentNode.textContent='${escapeHtml(initials(session))}'"/>`:escapeHtml(initials(session))}</span><span class="session-main"><b>${escapeHtml(name)}</b><em>${escapeHtml(originKind(session.origin))} · ${escapeHtml(session.last_seen||'-')}</em><small>${escapeHtml(session.origin)}</small><p>${escapeHtml(session.last_message_preview||'暂无预览')}</p></span></button>`}
function filteredFor(role){const keyword=role==='trigger'?$('sessionSearch').value:$('importSessionSearch').value;return usableSessions.filter(s=>sessionMatches(s,keyword)).slice(0,24)}
function renderSessionCards(role){const target=role==='trigger'?$('triggerSessionCards'):$('importSessionCards');if(!target)return;const sessions=filteredFor(role);target.innerHTML=sessions.map(s=>sessionCard(s,role)).join('')||'<div class="hint">暂无匹配会话。</div>'}
function renderSessions(sessions,rawSessions){fillSessionSelect($('sessionSelect'),sessions,selectedTriggerSession);fillSessionSelect($('importSessionSelect'),sessions,selectedImportSession);renderSessionCards('trigger');renderSessionCards('import');const filtered=(rawSessions||[]).length-sessions.length;const notice=filtered>0?`<div class="hint soft-note full-span">已隐藏 ${filtered} 个空会话：aiocqhttp/napcat 适配器会话、纯数字会话、数字_数字 会话。这些通常读不到有效历史，仍可手动输入测试。</div>`:'';$('sessionsList').innerHTML=notice+(sessions.map(session=>`<div class="session-card big static-card"><span class="avatar">${avatarUrl(session)?`<img src="${escapeHtml(avatarUrl(session))}"/>`:escapeHtml(initials(session))}</span><span class="session-main"><b>${escapeHtml(displayName(session))}</b><em>${escapeHtml(originKind(session.origin))} · ${escapeHtml(session.last_seen||'-')}</em><small>${escapeHtml(session.origin)}</small><p>${escapeHtml(session.last_message_preview||'暂无预览')}</p><span class="item-actions"><button class="link-btn" onclick="useSession('${escapeHtml(session.origin)}')">用于触发</button><button class="link-btn" onclick="previewHistory('${escapeHtml(session.origin)}')">预览历史</button><button class="link-btn" onclick="useImportSession('${escapeHtml(session.origin)}')">迁移到此</button></span></span></div>`).join('')||'<div class="hint">暂无可用会话记录。插件会在收到私聊/群聊消息时自动记录 unified_msg_origin。</div>')}
function renderActions(actions){$('actionsList').innerHTML=actions.map(action=>`<div class="list-item"><strong>${action.ok?'✅':'❌'} ${escapeHtml(action.command||action.kind||'action')}</strong><span>${escapeHtml(action.time||'')} · ${escapeHtml(action.session||action.target_origin||action.file||'')}</span><span>${escapeHtml(action.error||(action.files&&action.files.length?'files: '+action.files.join(', '):''))}</span></div>`).join('')||'<div class="hint">暂无 WebUI 操作记录。</div>'}
function renderConfig(cfg){if(!cfg||!cfg.ok){$('configBox').textContent='配置读取失败：'+(cfg&&cfg.error?cfg.error:'未知错误');return}const rows=Object.entries(cfg.config||{}).map(([key,value])=>{const meta=configLabels[key]||[key,''];const display=value===null||value===undefined||value===''?'未设置':String(value);return `<div class="config-item"><div class="config-main"><b>${escapeHtml(meta[0])}</b><span>${escapeHtml(display)}</span></div>${meta[1]?`<p>${escapeHtml(meta[1])}</p>`:''}<em>${escapeHtml(key)}</em></div>`}).join('');$('configBox').innerHTML=rows||'暂无配置'}
function fileLabel(file){const source=file.source_label||file.origin_label||file.origin||'未知来源';const stats=file.stats||{};const statText=stats.raw_count?` · ${stats.raw_count}/${stats.kept_count??'?'}条`:'';return `${file.name}  ·  来源：${source}${statText}`}
function renderImportOptions(){const cleanFiles=allFiles.filter(file=>file.migration_available||String(file.name||'').startsWith('memory_bridge_clean_'));$('importFileSelect').innerHTML=cleanFiles.map(file=>`<option value="${escapeHtml(file.name)}">${escapeHtml(fileLabel(file))}</option>`).join('');if(!cleanFiles.length)$('importFileSelect').innerHTML='<option value="">暂无可迁移记忆包；可执行 /续忆 clean_export balanced 或在 WebUI 外部导入 clean/migration zip</option>';restoreSelectValue($('importFileSelect'),selectedImportFile)}
function renderImports(imports){$('importsList').innerHTML=(imports||[]).map(item=>{const conv=item.conversation||{};const pm=item.plugin_memory||{};const stats=item.stats||{};return `<div class="list-item import-record"><strong>${escapeHtml(item.import_id||'-')} · ${escapeHtml(item.status||'-')}</strong><span>模式：${escapeHtml(item.mode||'-')} · 目标：${escapeHtml(item.target_label||item.target_origin||'-')}</span><span>来源：${escapeHtml(item.source_label||item.source_origin||'-')} · 文件：${escapeHtml(item.source_file||'')}</span><span>conversation：${escapeHtml(conv.conversation_id||'无')} · chunks：${escapeHtml(pm.chunks||0)} · 原始/保留：${escapeHtml(stats.raw_count??'?')} / ${escapeHtml(stats.kept_count??'?')}</span><span>时间：${escapeHtml(item.created_at||'')}</span><div class="item-actions"><button class="link-btn" onclick="copyText('${escapeHtml(item.import_id||'')}')">复制ID</button><button class="link-btn danger" onclick="rollbackImport('${escapeHtml(item.import_id||'')}')">回滚</button></div></div>`}).join('')||'<div class="hint">暂无导入记录。</div>'}
function currentSession(sync=true){const value=($('manualSession').value||'').trim() || $('sessionSelect').value;if(sync&&value){selectedTriggerSession=value;rememberSelections()}return value}
function currentImportSession(sync=true){const value=($('importManualSession').value||'').trim() || $('importSessionSelect').value;if(sync&&value){selectedImportSession=value;rememberSelections()}return value}
function chooseSession(role,origin){if(role==='trigger'){selectedTriggerSession=origin;$('sessionSelect').value=origin;$('manualSession').value='';renderSessionCards('trigger');switchPage('trigger')}else{selectedImportSession=origin;$('importSessionSelect').value=origin;$('importManualSession').value='';renderSessionCards('import');switchPage('migrate')}rememberSelections()}
function useSession(session){chooseSession('trigger',session)}
function useImportSession(session){chooseSession('import',session)}
function selectImportFile(name){selectedImportFile=name;$('importFileSelect').value=name;rememberSelections();switchPage('migrate');previewImport()}
function copyText(text){navigator.clipboard?.writeText(text).then(()=>alert('已复制：'+text)).catch(()=>prompt('复制以下内容',text))}
async function triggerCommand(){const session=currentSession();const command=$('commandSelect').value;const mode=$('modeSelect').value;if(!session){$('triggerMsg').textContent='没有可用会话。请先在目标会话里发送任意 /续忆 命令，或手动输入 origin。';switchPage('trigger');return}if(!confirm(`确认要在会话中触发 /续忆 ${command} 吗？\n\n目标：${session}`))return;$('triggerBtn').disabled=true;$('triggerMsg').textContent='正在触发，请稍候...';switchPage('trigger');try{const data=await api('/api/trigger',{method:'POST',body:JSON.stringify({session,command,mode})});$('triggerMsg').textContent=`触发成功：/续忆 ${command}\n会话：${session}\n文件：${(data.files||[]).join(', ')||'无'}`;await refreshAll();restoreSelectValue($('sessionSelect'),session);selectedTriggerSession=session;rememberSelections();renderSessionCards('trigger')}catch(error){$('triggerMsg').textContent='触发失败：'+error.message;await refreshAll().catch(()=>{})}finally{$('triggerBtn').disabled=false}}
async function inspectFile(name){$('inspectBox').textContent='正在检查 '+name+' ...';switchPage('inspect');try{const data=await api('/api/files/'+encodeURIComponent(name)+'/inspect');const samples=(data.samples||[]).map(sample=>`<div class="sample"><b>${escapeHtml(sample.role||'')}</b> <span>${escapeHtml(sample.time||'')}</span><p>${escapeHtml(sample.content||sample.content_preview||'')}</p></div>`).join('');$('inspectBox').innerHTML=`<h3>${escapeHtml(data.name)}</h3><div class="kv"><b>大小</b><span>${fmtBytes(data.size)}</span></div><div class="kv"><b>时间</b><span>${escapeHtml(data.mtime)}</span></div><h4>Manifest</h4><pre>${escapeHtml(JSON.stringify(data.manifest||{},null,2))}</pre><h4>Stats</h4><pre>${escapeHtml(JSON.stringify(data.stats||{},null,2))}</pre><h4>迁移信息</h4><pre>${escapeHtml(JSON.stringify(data.migration||{},null,2))}</pre><h4>样本</h4>${samples||'<div class="hint">无样本</div>'}<h4>文件条目</h4><pre>${escapeHtml((data.entries||[]).slice(0,40).map(entry=>entry.name+'  '+entry.size+' bytes').join('\n'))}</pre>`}catch(error){$('inspectBox').textContent='检查失败：'+error.message}}
async function deleteFile(name){if(!confirm('确认删除导出文件？\n'+name))return;try{await api('/api/files/'+encodeURIComponent(name),{method:'DELETE'});await refreshAll();$('inspectBox').textContent='已删除：'+name;switchPage('inspect')}catch(error){alert('删除失败：'+error.message)}}
async function previewHistory(session){session=session||currentSession();if(!session){$('inspectBox').textContent='没有会话可预览';switchPage('inspect');return}$('inspectBox').textContent='正在读取历史预览...';switchPage('inspect');try{const data=await api('/api/history-preview?session='+encodeURIComponent(session)+'&limit=20');$('inspectBox').innerHTML=`<h3>历史预览</h3><div class="kv"><b>会话</b><span>${escapeHtml(session)}</span></div><div class="kv"><b>来源</b><span>${escapeHtml(data.source)}</span></div><div class="kv"><b>数量</b><span>${escapeHtml(data.count)}</span></div>`+(data.messages||[]).map(message=>`<div class="sample"><b>#${message.index} ${escapeHtml(message.role||'')}</b> <span>${escapeHtml(message.time||'')}</span><p>${escapeHtml(message.content_preview||'')}</p></div>`).join('')}catch(error){$('inspectBox').textContent='历史预览失败：'+error.message}}
async function previewImport(){const filename=$('importFileSelect').value;if(filename){selectedImportFile=filename;rememberSelections()}if(!filename){$('importBox').textContent='暂无可预览 clean zip。';return}$('importBox').textContent='正在读取导入预览...';try{const data=await api('/api/import-preview?filename='+encodeURIComponent(filename));const warnings=(data.warnings||[]).map(warning=>`<li>${escapeHtml(warning)}</li>`).join('')||'<li>无</li>';$('importBox').innerHTML=`<h3>导入预览：${escapeHtml(data.file)}</h3><div class="kv"><b>来源用户</b><span>${escapeHtml(data.source_label||data.source_origin||'未知来源')}</span></div><div class="kv"><b>来源 origin</b><span>${escapeHtml(data.source_origin||'')}</span></div><div class="kv"><b>原始/保留</b><span>${escapeHtml((data.stats&&data.stats.raw_count)||'?')} / ${escapeHtml((data.stats&&data.stats.kept_count)||'?')}</span></div><div class="kv"><b>Seed 消息</b><span>${escapeHtml(data.seed_count)}</span></div><div class="kv"><b>Chunks</b><span>${escapeHtml(data.chunks_count)}</span></div><h4>警告</h4><ul>${warnings}</ul><h4>记忆卡预览</h4><pre>${escapeHtml(data.memory_card_preview||'')}</pre>`}catch(error){$('importBox').textContent='导入预览失败：'+error.message}}
async function runImport(){const filename=$('importFileSelect').value;const target=currentImportSession();const mode=$('importMode').value;if(!filename){$('importBox').textContent='请先选择 clean zip。';return}if(!target){$('importBox').textContent='请先选择或手动输入目标会话。';return}selectedImportFile=filename;selectedImportSession=target;rememberSelections();if(!confirm(`确认导入记忆？\n\n文件：${filename}\n目标：${target}\n模式：${mode}\n\n建议先在测试会话验证。`))return;$('importBox').textContent='正在导入，请稍候...';try{const data=await api('/api/import',{method:'POST',body:JSON.stringify({filename,target_origin:target,mode})});$('importBox').innerHTML=`<h3>导入完成</h3><div class="kv"><b>导入 ID</b><span>${escapeHtml(data.import_id)}</span></div><div class="kv"><b>模式</b><span>${escapeHtml(data.mode)}</span></div><div class="kv"><b>目标</b><span>${escapeHtml(data.target_origin)}</span></div><div class="kv"><b>新会话</b><span>${escapeHtml((data.conversation&&data.conversation.conversation_id)||'无')}</span></div><div class="kv"><b>长期记忆 chunks</b><span>${escapeHtml((data.plugin_memory&&data.plugin_memory.chunks)||0)}</span></div><pre>${escapeHtml(JSON.stringify(data,null,2))}</pre>`;await refreshAll();restoreSelectValue($('importSessionSelect'),target);restoreSelectValue($('importFileSelect'),filename);selectedImportSession=target;selectedImportFile=filename;rememberSelections();renderSessionCards('import')}catch(error){$('importBox').textContent='导入失败：'+error.message;await refreshAll().catch(()=>{})}}
async function rollbackImport(importId){if(!importId)return;if(!confirm('确认回滚导入？\n'+importId))return;try{const data=await api('/api/import-rollback',{method:'POST',body:JSON.stringify({import_id:importId})});$('importBox').innerHTML='<h3>回滚结果</h3><pre>'+escapeHtml(JSON.stringify(data,null,2))+'</pre>';switchPage('migrate');await refreshAll()}catch(error){alert('回滚失败：'+error.message)}}

document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>switchPage(btn.dataset.page)));
document.querySelectorAll('[data-quick]').forEach(btn=>btn.addEventListener('click',()=>{$('commandSelect').value=btn.dataset.quick;triggerCommand()}));
$('refreshBtn').addEventListener('click',refreshAll);
$('passwordSubmit').addEventListener('click',doLogin);
$('passwordInput').addEventListener('keydown',event=>{if(event.key==='Enter')doLogin()});
$('loginBtn').addEventListener('click',()=>showLogin());
$('logoutBtn').addEventListener('click',logout);
$('triggerBtn').addEventListener('click',triggerCommand);
$('historyPreviewBtn').addEventListener('click',()=>previewHistory());
$('importPreviewBtn').addEventListener('click',previewImport);
$('importRunBtn').addEventListener('click',runImport);
$('sessionSelect').addEventListener('change',()=>{selectedTriggerSession=$('sessionSelect').value;$('manualSession').value='';rememberSelections();renderSessionCards('trigger')});
$('importSessionSelect').addEventListener('change',()=>{selectedImportSession=$('importSessionSelect').value;$('importManualSession').value='';rememberSelections();renderSessionCards('import')});
$('importFileSelect').addEventListener('change',()=>{selectedImportFile=$('importFileSelect').value;rememberSelections()});
$('sessionSearch').addEventListener('input',()=>{fillSessionSelect($('sessionSelect'),filteredFor('trigger'),selectedTriggerSession);renderSessionCards('trigger')});
$('importSessionSearch').addEventListener('input',()=>{fillSessionSelect($('importSessionSelect'),filteredFor('import'),selectedImportSession);renderSessionCards('import')});
checkAuth().catch(error=>showLogin('连接 WebUI 后端失败：'+error.message));
